version: '2'
services:
  ml-blog:
    container_name: ml-blog
    restart: always
    #构建容器
    build: .
    ports:
    - "80:4000"
  nginx:
    restart: always
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d